# Generated by Django 5.0.1 on 2024-01-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_email', models.EmailField(max_length=254)),
                ('u_message', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='blog_category',
            name='blog_cat',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='blog_category',
            name='blogcat_description',
            field=models.CharField(max_length=200),
        ),
    ]
