# Generated by Django 5.0.1 on 2024-01-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0002_contact_info_alter_blog_category_blog_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_email', models.EmailField(max_length=254, unique=True)),
                ('u_membership', models.CharField(max_length=200)),
            ],
        ),
    ]
