# Generated by Django 5.0.1 on 2024-01-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='u_email',
            field=models.EmailField(max_length=254),
        ),
    ]
