# Generated by Django 5.0.1 on 2024-01-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0007_alter_blog_post_blog_descripiton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='blog_descripiton',
            new_name='blog_description',
        ),
    ]
